### ISSUE TITLE
PDF files not tracked in Web view

### ISSUE THREAD

**Issue by oparoz** [nextcloud/user_usage_report#14]
It seems PDF files are not tracked as being read when they're opened in the browser.
It should work since they need to be fed to the JS viewer.

**Comment by rullzer** [comment]
Works here. Do you have any more info?

**Comment by nickvergessen** [comment]
Same here, works as intended:

1. Load file index
2. Upload pdf
3. Before:
```
./occ usage-report:generate admin
"admin","2018-02-26T08:01:02+00:00",-2,32410,8,0,4,22
```
4. Click on file which opens the pdf viewer
5. After:
```
./occ usage-report:generate admin
"admin","2018-02-26T08:01:11+00:00",-2,32410,8,0,4,23
```

**Comment by oparoz** [comment]
Thank you for testing.
