### ISSUE TITLE
Not woking with external storage as primary storage

### ISSUE THREAD

**Issue by tomtomas99911** [nextcloud/user_usage_report#19]
Is there any chance please that this plugin will in future work with external primary storage? 
Now this plugin can show only quota and number of shares if you are using external primary storage...

**Comment by nickvergessen** [comment]
That should work already?

**Comment by nickvergessen** [comment]
Closing due to the lack of feedback

**Comment by FlyingAndrew** [comment]
Not 100% sure, if @tomtomas99911 meant this issue. But I'm also using an external storage as location for all data and the report runs in an integer overflow for the "Disk space consumed by home storage in bytes". It shows maximally 2147483647 (2**32-1, max of int32) but works if the storage is small than this.
