### ISSUE TITLE
Add last login time to the report.

### ISSUE THREAD

**Issue by derekblankmccoy** [nextcloud/user_usage_report#22]
I know its not strictly 'usage', but it does tell admins if he user is 'using' Nextcloud.
Don't know if it's possible but it is in the users view on the web console, so the info is somewhere.
Thanks.

**Comment by derekblankmccoy** [comment]
https://www.bountysource.com/issues/66474669-add-last-login-time-to-the-report

**Comment by derekblankmccoy** [comment]
Do I just download the zip and cp over to /apps?

**Comment by derekblankmccoy** [comment]
Not working:

> :/var/www/html$ sudo -u www-data ./occ usage-report:generate mccoyd
> "mccoyd","2018-11-28T11:44:38+00:00","1 B",0,0,0,0,0

**Comment by nickvergessen** [comment]
try:
```
$ sudo -u www-data ./occ usage-report:generate --last-login mccoyd
```

I didn't add it by default, but only optional, so it doesn't break existing parsers

**Comment by derekblankmccoy** [comment]
Ok, that worked. What do I modify to add it by default?
Ill wait for some more users to login and try exporting it to a csv file
Might also want to remove the other bits by default if its easy enough to do by modifying a file. Thanks.

**Comment by nickvergessen** [comment]
You can remove other entries by removing them from the print method in https://github.com/nextcloud/user_usage_report/blob/master/lib/Formatter.php#L32

**Comment by nickvergessen** [comment]
To always add it, add 
```php
$input->setOption('last-login', true);
```
after line 100:
https://github.com/nextcloud/user_usage_report/blob/ea952e1d63bd305fa57e4b05b131508d92b9626a/lib/Command/Generate.php#L100

**Comment by derekblankmccoy** [comment]
Ok, cool. I guess removing line 40 and 42 from Formatter.php would work too?

**Comment by nickvergessen** [comment]
No, because the data is not fetched then ;)

**Comment by derekblankmccoy** [comment]
Ill stick to being a Photographer, lol.

**Comment by derekblankmccoy** [comment]
Ok, making it default worked. I just want to remove the timestamp so commenting out Line 39 on Formatter.php should do it right?

**Comment by nickvergessen** [comment]
Yes

**Comment by derekblankmccoy** [comment]
Nice. Thanks for your help, have a few beers.
