### ISSUE TITLE
the report-app shows deleted users

### ISSUE THREAD

**Issue by MADXhh** [nextcloud/user_usage_report#31]
the report-app shows deleted users. 
why are they listed? Is it possible to delete this (old) user from the report? 
And how can i switch to KB or GB instead of Bytes?
Thanks

**Comment by nickvergessen** [comment]
> And how can i switch to KB or GB instead of Bytes?

I guess we can do that once #29 is implementing different output formats and one should be "plain" aka human readable.

**Comment by nickvergessen** [comment]
> why are they listed?

I guess because they have entries in the table which was used back in the days.
But since the table is not used anymore, I can also no longer reproduce this. So it was fixed by #40
