### ISSUE TITLE
Can't update to v1.2.1

### ISSUE THREAD

**Issue by vascowhite** [nextcloud/user_usage_report#44]
I tried to update this app today, but got an error message. I tried both the browser and occ with the same result.

### Steps to reproduce
1.Try to update in the browser
2. Try to update with occ
3.

### Expected behaviour
Tell us what should happen

The app should update

### Actual behaviour
Tell us what happens instead

An error is shown

    occ app:update --all -vvv
    user_usage_report new version available: 1.2.1
    user_usage_report couldn't be updated

### Server configuration

**Operating system**:
Debian 10.4 Buster

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.3.19

**Nextcloud version:** (see Nextcloud admin page)
18.0.6

**Where did you install Nextcloud from:**
Updater

**List of activated apps:**

  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.10.0
  - bookmarks: 3.2.4
  - bookmarks_fulltextsearch: 1.2.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.4
  - documentserver_community: 0.1.7
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_markdown: 2.3.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 1.0.0
  - forms: 1.1.1
  - fulltextsearch_elasticsearch: 1.5.1
  - groupfolders: 6.0.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.6
  - metadata: 0.11.1
  - news: 14.1.11
  - nextcloud_announcements: 1.7.0
  - notes: 3.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 6.0.43
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - quicknotes: 0.6.0
  - recommendations: 0.6.0
  - scanner: 0.1.9
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - user_usage_report: 1.2.0
  - viewer: 1.2.0
  - workflow_script: 1.3.2
  - workflowengine: 2.0.0

```

**Comment by vascowhite** [comment]
Just saw this in `info.xml`

    <dependencies>
        <nextcloud min-version="20" max-version="20" />
    </dependencies>

I guess that's the problem?

**Comment by nickvergessen** [comment]
Yeah, the uodate was removed due to #39
But new releases have been pushed like 30 minutes ago, so it just might need some time until your instance cache is refreshed

**Comment by vascowhite** [comment]
Thanks for the quick response.
