### ISSUE TITLE
user_usage_report doesn't provide report for all users.

### ISSUE THREAD

**Issue by ajrossnz** [nextcloud/user_usage_report#7]
### Steps to reproduce
1. sudo -u www-data ./occ usage-report:generate

2.gives an error saying uid must not be an empty string.

All user logins are via LDAP.

### Expected behaviour
should create a list of all user activity

### Actual behaviour
InvalidArgumentException is thrown and error is as above 2).

### Server configuration

**Operating system**:
Debian 8.9
**Web server:**
Apache 2.4.10

**Database:**
Mysql 5.5.57.0+deb8u1

**PHP version:**
5.6.30
**Nextcloud version:** (see Nextcloud admin page)
12.3
**Where did you install Nextcloud from:**
dpkg (I think).

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
can you please post the full error message and also look into your data/nextcloud.log file for the full error message and stacktrace?

**Comment by nickvergessen** [comment]
Closing due to the lack of feedback
