### ISSUE TITLE
After NC 22 Docker Upgrade, Database Error when trying to preview images/SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax

### ISSUE THREAD

**Issue by AlexG-78** [nextcloud/user_usage_report#71]
### Actual Behaviour
I have upgraded to latest NC 22.0.0.11 on docker with FPM. When I try to preview images, I receive an SQL Error:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ‘configvalue + 1) WHERE (userid = ‘USERNAME’) AND (configkey = ‘read’) AND (…’ at line 1

I already deleted all image previews from appdata forler and in the databaye, also tried to repair the previews and recalculated them. No changes.

### Expected behaviour
Images should be previews withour any Error

### Server configuration
Debian 10
Docker image with FPM/NGINX and Apache reverse proxy
8GB RAM
MariaDB 10.6
PHP-FPM 7.4

**Nextcloud version:** (see Nextcloud admin page)
22.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:**
21.0.3
**Where did you install Nextcloud from:**
Docker Repo

**Comment by nickvergessen** [comment]
It's a server issue, already fixed for next release of Nextcloud itself, see #69 for more infos
