### ISSUE TITLE
Command option to add CSV header

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/user_usage_report#73]
It would be useful to have a boolean flag, ex  `--header true| false`, to include the header in the CSV file.

```
$ sudo -u www-data php ./occ usage-report:generate --header true -- nc-user1
"user","current_date","last_login","assigned_storage","consumed_storage","n_files","n_shares","n_new_files","n_files_read"
"nc-user1","2021-08-30T15:48:27+00:00",5368709120,0,6,1,33,7
```

This makes the data ingestion operation easier, if the call to `occ usage-report:generate` is followed by a data transformation pipeline, for example insert data in a relational database for later analysis.

If this is going to be implemented, please avoid spaces in the header.

**Comment by nickvergessen** [comment]
Try `--verbose`?

**Comment by pmarini-nc** [comment]
Thanks for the quick reply.

The output of ``--verbose`` (didn't find the documentation on it nor in the command help, maybe a flag that applies to many occ commands?) is almost what I'm looking for.

```
$ sudo -u www-data php ./occ usage-report:generate --verbose -- nc-user1
[sudo] password for unc: 
"user-id","date as 'c'","assigned quota (5 GB)","used quota (500 MB)",number of files,number of shares,number of uploads,number of downloads,
"nc-user1","2021-08-30T16:38:46+00:00",5368709120,277,14,1,35,23
```

However, there are two problems here:

- the comma after `number of downloads` shouldn't be there as it makes it harder for the csv parser to parse the file correctly
- mix of quoted/bare column names. As mentioned above, it is much better to use underscores instead of spaces and avoid special characters like `'` in the header

**Comment by nickvergessen** [comment]
> didn't find the documentation on it nor in the command help, maybe a flag that applies to many occ commands?

Yes, it applies/is-defined on all commands, but on some it is not used.

![Bildschirmfoto von 2021-08-30 18-57-07](https://user-images.githubusercontent.com/213943/131376242-e4f97d66-e7c6-44ce-b315-12b983a92a53.png)

I get your comment about the headers and will think how to solve it without breaking the pattern.

**Comment by bernd-wechner** [comment]
I'd document this in the README if I were you and here:

https://apps.nextcloud.com/apps/user_usage_report
