### ISSUE TITLE
Suppress progress output

### ISSUE THREAD

**Issue by jmcclelland** [nextcloud/user_usage_report#75]
### Steps to reproduce
1. Run report on all users
2. Redirect output to a file
3. The progress bar output creates garbage at top of file

### Expected behaviour
It would be a nice feature to have an option that disables the progress bar

### Actual behaviour
I can't find any way to disable this output

I'd like to run this command via a timed script and parse the output, but the progress data makes that more complicated.

Thanks!

**Comment by nickvergessen** [comment]
Which progress output?

**Comment by jmcclelland** [comment]
When I run the report for all users I get a text-based progress bar made up of dashes and right angle brackets at the top of the output. See screen shot below:

![progress-output](https://user-images.githubusercontent.com/4511942/132010450-02c72e20-2857-4b49-b101-1217afca0a13.png)

**Comment by nickvergessen** [comment]
That's not from this app. Can you post your applist?
By chance do you have circles installed and can try to disable it?

**Comment by jmcclelland** [comment]
I tried disabling circles and it had no effect.

Then, I commented out every line with `$progress->advance()` in the `lib/Reports/AllUsers.php` and that made it go away.

**Comment by nickvergessen** [comment]
Ah hmm that should only print when you have many users to give a progress feeling as generating the report could take quite some time

**Comment by nickvergessen** [comment]
if you pipe the output to a file only the data is put into the file and the progress will be shown in the 

```
occ usage-report:generate > test.txt
    2 [->--------------------------]  1 sec
```
After the end of the command you can `cat test.txt` to print the content to copy it out if you don't want it in a file on your server.
