### ISSUE TITLE
Enhancement tip: add a small installation instruction

### ISSUE THREAD

**Issue by mrAceT** [nextcloud/user_usage_report#82]
This was the first time I wanted to install an app manually.. and it might be an idea to add a few lines to the README.md like:

# Installation
1. Download correct version (download link via version number): https://apps.nextcloud.com/apps/user_usage_report
2. extract the tar.gz into your nextcloud/apps/ folder
3. check that your apps folder now contains a folder with the name 'user_usage_report'
4. enable the app via the web interface

All not very difficult, but if you've never done it this little instruction would have saved me some time ;)

**Comment by nickvergessen** [comment]
Actually what you would do is go to the app management in your nextcloud: `index.php/settings/apps/monitoring` and install the app there with a simple button click

**Comment by mrAceT** [comment]
Ah! Even better, put that into the readme!
