### ISSUE TITLE
Include Full Name of user in the export

### ISSUE THREAD

**Issue by pbhenny** [nextcloud/user_usage_report#9]
### Steps to reproduce
1. sudo -u www-data ./occ usage-report:generate

### Expected behaviour
It works! This is a request to include Full Name user in the export.

### Actual behaviour
Nothing

### Server configuration

**Operating system**:
Debian 8.7
**Web server:**
Apache 2.4.10
**Database:**
Mariadb
**PHP version:**
5.6.3
**Nextcloud version:** 
12.3

### Client configuration
**Browser:**
Safari
**Operating system:**
Mac os X

**Comment by damienvancouver** [comment]
I have created a fork that has this functionality - see https://github.com/damienvancouver/user_usage_report ,  and a pull request #26 .

**Comment by louis378** [comment]
+1

**Comment by nickvergessen** [comment]
Merged via https://github.com/nextcloud/user_usage_report/pull/65
