### ISSUE TITLE
Option to write output to file

### ISSUE THREAD

**Issue by tomotello** [nextcloud/user_usage_report#91]
### Enhancement request
For running user usage report in Panel managed environments (like Plesk) via php cron scheduler it would be nice to have an --output option. (shell redirection  > | 2>&1 don't work in such a context).

**Comment by solracsf** [comment]
I would suggest `--location=[FULL_PATH]` because of https://github.com/nextcloud/user_usage_report/issues/29

**Comment by nickvergessen** [comment]
Makes sense to have, naming is a minor detail, but yeah output should be used for the format as it is used by many other commands already since a long time

**Comment by nickvergessen** [comment]
Added in https://github.com/nextcloud/user_usage_report/pull/131

`--output-file=/absolute/path/to/file.txt` is now supported
